<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Learn English</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://vk.com/js/api/openapi.js?154" type="text/javascript"></script>

  <link href="css/bootstrap.css" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">
  
  
  
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
              background-color: #161351;

    }
    
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #161351;
      padding: 25px;
        color:#E0FFFF;
    }
    
  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; 
    }
    </style>
      <body>
      <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#" >Learn English</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="index.php">Главная</a></li>        
       <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Материалы
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="articles.php">Статьи</a></li>
          <li><a href="videos.php">Видео</a></li>
          <li><a href="audio.php">Аудио</a></li>
        </ul>
      </li>
      <li><a href="ulinks.php">Полезные ссылки</a></li>  ,
       <li><a href="about.php">О нас</a></li>  ,
        <li><a href="support.php">Обратная связь</a></li>     
      </ul>
    </div>
  </div>
</nav>
    </body>
     <!-- </ul>
    </div>
  </div>
</nav>-->
</head>
</html>